In [1]:
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np

In [2]:
tickers = ['AAPL', 'MSFT', 'XOM', 'TSLA', 'GC=F']
df = yf.download(tickers, start='2023-01-01', end='2024-12-31')
df = df['Close'].dropna()
df = df.rename(columns={'AAPL':'Apple', 'GC=F':'Gold', 'MSFT':'Microsoft', 'TSLA':'Tesla', 'XOM':'Exxon Mobil'})

C:\Users\arthu\AppData\Local\Temp\ipykernel_21192\3032578394.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(tickers, start='2023-01-01', end='2024-12-31')
[*********************100%***********************]  5 of 5 completed


In [3]:
df_returns = pd.DataFrame()
df_returns['Apple'] = np.log(df['Apple']/df['Apple'].shift(1))
df_returns['Micrsoft'] = np.log(df['Microsoft']/df['Microsoft'].shift(1))
df_returns['Gold'] = np.log(df['Gold']/df['Gold'].shift(1))
df_returns['Tesla'] = np.log(df['Tesla']/df['Tesla'].shift(1))
df_returns['Exxon Mobil'] = np.log(df['Exxon Mobil']/df['Exxon Mobil'].shift(1))
df_returns = df_returns.dropna()

In [4]:
allocations = np.array([[0.2, 0.2, 0.2, 0.2, 0.2], [0.35, 0.35, 0.1, 0.1, 0.1], [0.1, 0.1, 0.1, 0.1, 0.6]])
portfolios = pd.DataFrame(allocations, columns=['Apple', 'Microsoft', 'Gold', 'Tesla', 'Exxon Mobil'])

In [5]:
mean_ann_returns = df_returns.mean()*252*100
cov_matrix = df_returns.cov()*252

In [6]:
port_ann_return = np.dot(allocations, mean_ann_returns)
port_volatility = []
for w in allocations:
    vol = np.sqrt(np.dot(w.T,np.dot(cov_matrix,w)))
    port_volatility.append(vol)
port_volatility = np.array(port_volatility)*100

In [7]:
#Risk free rate
rf = 0 
Sharpe_ratios = (port_ann_return - rf)/port_volatility

In [8]:
print(port_ann_return)
print(port_volatility)
print(Sharpe_ratios)

[30.84683983 31.81462709 16.93663593]
[16.98353499 16.72592175 15.55798901]
[1.81627911 1.90211503 1.08861344]
